---
apiVersion: v1
kind: Namespace
metadata:
  name: kubesmith-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesmith-operator-controller-manager
  namespace: kubesmith-system
  labels:
    app: kubesmith-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: kubesmith-operator
        control-plane: controller-manager
    spec:
      serviceAccountName: kubesmith-operator-controller-manager
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: docker.io/kubesmith/kubesmith-operator:latest
          imagePullPolicy: IfNotPresent
          command: [/manager]
          args:
            - --leader-elect
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: healthz
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      terminationGracePeriodSeconds: 10
