//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ── AppDeployment ─────────────────────────────────────────────────────────────

func (in *AppDeployment) DeepCopyInto(out *AppDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AppDeployment) DeepCopy() *AppDeployment {
	if in == nil {
		return nil
	}
	out := new(AppDeployment)
	in.DeepCopyInto(out)
	return out
}

func (in *AppDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── AppDeploymentList ─────────────────────────────────────────────────────────

func (in *AppDeploymentList) DeepCopyInto(out *AppDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppDeploymentList) DeepCopy() *AppDeploymentList {
	if in == nil {
		return nil
	}
	out := new(AppDeploymentList)
	in.DeepCopyInto(out)
	return out
}

func (in *AppDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── AppDeploymentSpec ─────────────────────────────────────────────────────────

func (in *AppDeploymentSpec) DeepCopyInto(out *AppDeploymentSpec) {
	*out = *in
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmSpec)
		**out = **in
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *AppDeploymentSpec) DeepCopy() *AppDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(AppDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// ── AppDeploymentStatus ───────────────────────────────────────────────────────

func (in *AppDeploymentStatus) DeepCopyInto(out *AppDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastDeployedAt != nil {
		in, out := &in.LastDeployedAt, &out.LastDeployedAt
		*out = (*in).DeepCopy()
	}
}

func (in *AppDeploymentStatus) DeepCopy() *AppDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(AppDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// ── HelmSpec ──────────────────────────────────────────────────────────────────

func (in *HelmSpec) DeepCopyInto(out *HelmSpec) {
	*out = *in
}

func (in *HelmSpec) DeepCopy() *HelmSpec {
	if in == nil {
		return nil
	}
	out := new(HelmSpec)
	in.DeepCopyInto(out)
	return out
}

// ── AppMonitor ────────────────────────────────────────────────────────────────

func (in *AppMonitor) DeepCopyInto(out *AppMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AppMonitor) DeepCopy() *AppMonitor {
	if in == nil {
		return nil
	}
	out := new(AppMonitor)
	in.DeepCopyInto(out)
	return out
}

func (in *AppMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── AppMonitorList ────────────────────────────────────────────────────────────

func (in *AppMonitorList) DeepCopyInto(out *AppMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppMonitorList) DeepCopy() *AppMonitorList {
	if in == nil {
		return nil
	}
	out := new(AppMonitorList)
	in.DeepCopyInto(out)
	return out
}

func (in *AppMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── AppMonitorSpec ────────────────────────────────────────────────────────────

func (in *AppMonitorSpec) DeepCopyInto(out *AppMonitorSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsSpec)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]AlertRule, len(*in))
		copy(*out, *in)
	}
}

func (in *AppMonitorSpec) DeepCopy() *AppMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(AppMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// ── AppMonitorStatus ──────────────────────────────────────────────────────────

func (in *AppMonitorStatus) DeepCopyInto(out *AppMonitorStatus) {
	*out = *in
	if in.LastReconciledAt != nil {
		in, out := &in.LastReconciledAt, &out.LastReconciledAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppMonitorStatus) DeepCopy() *AppMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(AppMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// ── MetricsSpec ───────────────────────────────────────────────────────────────

func (in *MetricsSpec) DeepCopyInto(out *MetricsSpec) { *out = *in }

func (in *MetricsSpec) DeepCopy() *MetricsSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// ── AlertRule ─────────────────────────────────────────────────────────────────

func (in *AlertRule) DeepCopyInto(out *AlertRule) { *out = *in }

func (in *AlertRule) DeepCopy() *AlertRule {
	if in == nil {
		return nil
	}
	out := new(AlertRule)
	in.DeepCopyInto(out)
	return out
}
